#!/bin/sh

case "$1" in
	remove|abort-install|abort-upgrade)
		# This package is being removed, but its configuration has not yet
		# been purged.

		;;

	purge)
		rm -Rf /etc/homegear/devices/0 > /dev/null 2>&1
		rm -f /var/lib/homegear/modules/mod_homematicbidcos.so > /dev/null 2>&1
        ;;

	disappear)
		;;

	upgrade)
		;;

	failed-upgrade)
		;;

	*) echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;;
esac

exit 0

#DEBHELPER#
